<?php

namespace Nsure\Services;

/**
 * This class is onzup service for Permissions.
 */
class Permission
{
    private $modules = [
        'users' => [
            'users.list',
            'users.view',
            // 'users.add',
            'users.edit',
            'users.autologin',
            'users.info',
            // 'users.admin_dashboard',
            // 'users.superadmin',
        ],
        'roles' => [
            'roles.list',
            'roles.add',
            'roles.edit',
            'roles.delete',
        ],
        'dms' => [
            'dms.list',
            'dms.add',
            'dms.edit',
            'dms.view',
        ],
        'settings' => [
            'settings.view',
            // 'settings.Edit_past_entry',
            // 'settings.account_last_balance',
        ],

        //Master
        'country' => [
            'country.list',
            'country.add',
            'country.edit',
            'country.delete',
        ],
        'state' => [
            'state.list',
            'state.add',
            'state.edit',
            'state.delete',
        ],
        'currency' => [
            'currency.list',
            'currency.add',
            'currency.edit',
            'currency.delete',
        ],
        'years' => [
            'years.list',
            'years.add',
            'years.edit',
            'years.delete',
            // 'years.select_past_year',
        ],
        'smtp_configuration' => [
            'smtp_configuration.list',
            'smtp_configuration.add',
            'smtp_configuration.edit',
            'smtp_configuration.delete',
        ],
        'mail_template' => [
            'mail_template.list',
            'mail_template.add',
            'mail_template.edit',
            'mail_template.delete',
        ],
        'financing_sources' => [
            'financing_sources.list',
            'financing_sources.add',
            'financing_sources.edit',
            'financing_sources.delete',
        ],
        'bond_types' => [
            'bond_types.list',
            'bond_types.add',
            'bond_types.edit',
            'bond_types.delete',
        ],
        'insurance_companies' => [
            'insurance_companies.list',
            'insurance_companies.add',
            'insurance_companies.edit',
            'insurance_companies.delete',
        ],
        'file_source' => [
            'file_source.list',
            'file_source.add',
            'file_source.edit',
            'file_source.delete',
        ],
        'designation' => [
            'designation.list',
            'designation.add',
            'designation.edit',
            'designation.delete',
        ],
        'principle_type' => [
            'principle_type.list',
            'principle_type.add',
            'principle_type.edit',
            'principle_type.delete',
        ],
        'document_type' => [
            'document_type.list',
            'document_type.add',
            'document_type.edit',
            'document_type.delete',
        ],
        'trade_sector' => [
            'trade_sector.list',
            'trade_sector.add',
            'trade_sector.edit',
            'trade_sector.delete',
        ],
        'agent' => [
            'agent.list',
            'agent.add',
            'agent.edit',
            'agent.delete',
        ],
        'broker' => [
            'broker.list',
            'broker.add',
            'broker.edit',
            'broker.delete',
        ],
        'relevant_approval' => [
            'relevant_approval.list',
            'relevant_approval.add',
            'relevant_approval.edit',
            'relevant_approval.delete',
        ],
        'facility_type' => [
            'facility_type.list',
            'facility_type.add',
            'facility_type.edit',
            'facility_type.delete',
        ],
        're_insurance_grouping'=>[
            're_insurance_grouping.list',
            're_insurance_grouping.add',
            're_insurance_grouping.edit',
        ],
        'project_type' => [
            'project_type.list',
            'project_type.add',
            'project_type.edit',
            'project_type.delete',
        ],
        'banking_limit_categories' => [
            'banking_limit_categories.list',
            'banking_limit_categories.add',
            'banking_limit_categories.edit',
            'banking_limit_categories.delete',
        ],
        'underwriter' => [
            'underwriter.list',
            'underwriter.view',
            'underwriter.add',
            'underwriter.edit',
            'underwriter.delete',
        ],
        'principle' => [
            'principle.list',
            'principle.view',
            'principle.add',
            'principle.edit',
            // 'principle.delete',
            'principle.add_letter_of_award',
            'principle.edit_letter_of_award',
            'principle.import',
            'principle.initiate_review',
        ],
        // 'bond' => [
        //     'bond.list',
        //     'bond.view',
        // ],
        // 'bid_bond' => [
        //     'bid_bond.list',
        //     'bid_bond.view',
        //     'bid_bond.add',
        //     'bid_bond.edit',
        //     'bid_bond.delete',
        //     'bid_bond.edit_bond_number',
        //     'bid_bond.bond_issue_checklist',
        //     'bid_bond.nbi_view',
        //     'bid_bond.terms_sheet',
        //     'bid_bond.issue_bond',
        //     'bid_bond.invocation_notification',
        //     'bid_bond.add_bond_progress',
        //     'bid_bond.view_bond_progress',
        //     'bid_bond.add_bond_closure',
        //     'bid_bond.view_bond_closure',
        //     'bid_bond.add_bond_cancel',
        //     'bid_bond.view_bond_cancel',
        //     'bid_bond.invocation_claim',
        // ],
        'beneficiary' => [
            'beneficiary.list',
            'beneficiary.view',
            'beneficiary.add',
            'beneficiary.edit',
            // 'beneficiary.delete',
            'beneficiary.import',
        ],
        'type_of_entities' => [
            'type_of_entities.list',
            'type_of_entities.add',
            'type_of_entities.edit',
            'type_of_entities.delete',
        ],
        'proposals' => [
            'proposals.list',
            'proposals.view',
            'proposals.add',
            'proposals.edit',
            'proposals.terms_sheet',
            'proposals.confirm',
            'proposals.nbi_list',
            'proposals.bond_issue_checklist',
            'proposals.invocation_notification',
            'proposals.issue_bond',
            'proposals.bond_progress',
            'proposals.bond_fore_closure',
            'proposals.bond_cancellation',
            'proposals.intermediary'
        ],
        'nbi' => [
            'nbi.view',
            'nbi.status',
        ],
        'establishment_types' => [
            'establishment_types.list',
            'establishment_types.add',
            'establishment_types.edit',
            'establishment_types.delete',
        ],
        'ministry_types' => [
            'ministry_types.list',
            'ministry_types.add',
            'ministry_types.edit',
            'ministry_types.delete',
        ],
        // 'tenure' => [
        //     'tenure.list',
        //     'tenure.view',
        //     'tenure.add',
        //     'tenure.edit',
        //     'tenure.delete',
        // ],
        'tender' => [
            'tender.list',
            'tender.view',
            'tender.add',
            'tender.edit',
            'tender.delete',
            'tender.import',
        ],
        'bond_policies_issue' => [
            'bond_policies_issue.list',
            'bond_policies_issue.view',
            'bond_policies_issue.bond_number',
        ],
        // 'performance_bond' => [
        //     'performance_bond.list',
        //     'performance_bond.view',
        //     'performance_bond.add',
        //     'performance_bond.edit',
        //     'performance_bond.delete',
        //     'performance_bond.nbi_view',
        //     'performance_bond.terms_sheet',
        //     'performance_bond.issue_bond',
        //     'performance_bond.bond_issue_checklist',
        //     'performance_bond.edit_bond_number',
        //     'performance_bond.invocation_notification',
        //     'performance_bond.add_bond_progress',
        //     'performance_bond.view_bond_progress',
        //     'performance_bond.add_bond_closure',
        //     'performance_bond.view_bond_closure',
        //     'performance_bond.add_bond_cancel',
        //     'performance_bond.view_bond_cancel',
        //     'performance_bond.invocation_claim',
        // ],
        'employee' => [
            'employee.list',
            'employee.add',
            'employee.edit',
            'employee.delete',
        ],
        'cases'=>[
            'cases.list',
            'cases.view',
            // 'cases.add',
            // 'cases.edit',
            'cases.delete',
            'cases.synopsis',
            'cases.decision',
            'cases.parameter',
            'cases.action_plan',
            'cases.contractor',
            'cases.contractor',
            'cases.beneficiary',
            'cases.tender',
            'cases.banking_details',
            'cases.project_details',
            'cases.approved_limits',
            'cases.group_approved_limit',
            'cases.dms',
            'cases.incharge_log',
            'cases.invocation_details',
            'cases.last_5_year_track_record',
            'cases.order_book_and_future_projects',
            'cases.adverse_information'
            
        ],
        'relationship_manager' => [
            'relationship_manager.list',
            'relationship_manager.add',
            'relationship_manager.edit',
            'relationship_manager.delete',
        ],
        'group' => [
            'group.list',
            'group.add',
            'group.edit',
            'group.view',
            'group.delete',
        ],
        'work_type' => [
            'work_type.list',
            'work_type.add',
            'work_type.edit',
            'work_type.delete',
        ],
        'reason' => [
            'reason.list',
            'reason.add',
            'reason.edit',
            'reason.delete',
        ],
        'uw-view' => [
            'uw-view.list',
            'uw-view.add',
            'uw-view.edit',
            'uw-view.delete',
        ],
        'hsn-code' => [
            'hsn-code.list',
            'hsn-code.add',
            'hsn-code.edit',
            'hsn-code.delete',
        ],
        'issuing_office_branch' => [
            'issuing_office_branch.list',
            'issuing_office_branch.add',
            'issuing_office_branch.edit',
            'issuing_office_branch.delete',
            'issuing_office_branch.import',
        ],
        // 'bond-nbi' => [
        //     'bond-nbi.list',
        //     'bond-nbi.add',
        //     'bond-nbi.edit',
        //     'bond-nbi.view',
        //     'bond-nbi.delete',
        // ],

        // 'advance_payment_bond' => [
        //     'advance_payment_bond.list',
        //     'advance_payment_bond.add',
        //     'advance_payment_bond.edit',
        //     'advance_payment_bond.view',
        //     'advance_payment_bond.delete',
        //     'advance_payment_bond.bond_issue_checklist',
        //     'advance_payment_bond.edit_bond_number',
        //     'advance_payment_bond.nbi_view',
        //     'advance_payment_bond.terms_sheet',
        //     'advance_payment_bond.issue_bond',
        //     'advance_payment_bond.invocation_notification',
        //     'advance_payment_bond.add_bond_progress',
        //     'advance_payment_bond.view_bond_progress',
        //     'advance_payment_bond.add_bond_closure',
        //     'advance_payment_bond.view_bond_closure',
        //     'advance_payment_bond.add_bond_cancel',
        //     'advance_payment_bond.view_bond_cancel',
        //     'advance_payment_bond.invocation_claim',
        // ],

        // 'retention_bond' => [
        //     'retention_bond.list',
        //     'retention_bond.add',
        //     'retention_bond.edit',
        //     'retention_bond.view',
        //     'retention_bond.delete',
        //     'retention_bond.bond_issue_checklist',
        //     'retention_bond.edit_bond_number',
        //     'retention_bond.nbi_view',
        //     'retention_bond.terms_sheet',
        //     'retention_bond.issue_bond',
        //     'retention_bond.invocation_notification',
        //     'retention_bond.add_bond_progress',
        //     'retention_bond.view_bond_progress',
        //     'retention_bond.add_bond_closure',
        //     'retention_bond.view_bond_closure',
        //     'retention_bond.add_bond_cancel',
        //     'retention_bond.view_bond_cancel',
        //     'retention_bond.invocation_claim',
        // ],

        // 'maintenance_bond' => [
        //     'maintenance_bond.list',
        //     'maintenance_bond.add',
        //     'maintenance_bond.edit',
        //     'maintenance_bond.view',
        //     'maintenance_bond.delete',
        //     'maintenance_bond.bond_issue_checklist',
        //     'maintenance_bond.edit_bond_number',
        //     'maintenance_bond.nbi_view',
        //     'maintenance_bond.terms_sheet',
        //     'maintenance_bond.extension',
        //     'maintenance_bond.issue_bond',
        //     'maintenance_bond.invocation_notification',
        //     'maintenance_bond.add_bond_progress',
        //     'maintenance_bond.view_bond_progress',
        //     'maintenance_bond.add_bond_closure',
        //     'maintenance_bond.view_bond_closure',
        //     'maintenance_bond.add_bond_cancel',
        //     'maintenance_bond.view_bond_cancel',
        //     'maintenance_bond.invocation_claim',
        // ],

        // 'additional_bond' => [
        //     'additional_bond.list',
        //     'additional_bond.add',
        //     'additional_bond.edit',
        //     'additional_bond.view',
        //     'additional_bond.delete',
        // ],

        'rejection_reason' => [
            'rejection_reason.list',
            'rejection_reason.add',
            'rejection_reason.edit',
            'rejection_reason.delete',
        ],
        'premium' => [
            'premium.list',
            'premium.view',
        ],        
        'invocation_notification' => [
            'invocation_notification.list',
            'invocation_notification.add',
            'invocation_notification.view',
            // 'invocation_notification.payout',
            // 'invocation_notification.invocatiom_cancellelation',
            'invocation_notification.claim_examiner',
            'invocation_notification.intimation_invocation_details',
            'invocation_notification.contractor',
            'invocation_notification.analysis',
            'invocation_notification.decision',
            'invocation_notification.dms',
            'invocation_notification.previous_invocation',
            'invocation_notification.recovery',
            'invocation_notification.incharge_log',
        ],
        'recovery' => [
            'recovery.list',
            'recovery.add',
            'recovery.view',
        ],
        // 'invocation_claims' => [
        //     'invocation_claims.list',
        //     'invocation_claims.add',
        //     'invocation_claims.edit',
        //     'invocation_claims.view',
        //     'invocation_claims.delete',
        // ],         

        'adverse_information' => [
            'adverse_information.list',
            'adverse_information.add',
            'adverse_information.edit',
            'adverse_information.view',
            'adverse_information.delete',
        ],

        'blacklist' => [
            'blacklist.list',
            'blacklist.add',
            'blacklist.edit',
            'blacklist.view',
            'blacklist.delete',
        ],

        'agency' => [
            'agency.add',
            'agency.list',
            'agency.edit',
            'agency.delete',
        ],

        'agency-rating' => [
            'agency-rating.list',
            'agency-rating.add',
            'agency-rating.edit',
            'agency-rating.delete',
        ],

        'project-details' => [
            'project-details.list',
            'project-details.add',
            'project-details.edit',
            'project-details.view',
            'project-details.delete',
        ],

        'type_of_foreclosure' => [
            'type_of_foreclosure.list',
            'type_of_foreclosure.add',
            'type_of_foreclosure.edit',
            'type_of_foreclosure.delete',
        ],

        'invocation_reason' => [
            'invocation_reason.list',
            'invocation_reason.add',
            'invocation_reason.edit',
            'invocation_reason.delete',
        ],

        'claim_examiner' => [
            'claim_examiner.list',
            'claim_examiner.add',
            'claim_examiner.edit',
            'claim_examiner.view',
            'claim_examiner.delete',
        ],
        'reports' => [
            'contractor_wise.list',
            'bond_type_wise.list',
            'beneficiary_wise.list',
            'project_details_wise.list',
            'tender_wise.list',
        ],
    ];
    public function getPermissions()
    {
        return $this->modules;
    }
}
