<?php

return [
    'langs' => ['en' => "English", 'gu' => "ગુજરાતી", 'hi' => 'हिंदी'],
    'bank_list' => [
        "1" => "Allahabad Bank",
        "2" => "Andhra Bank",
        "3" => "Axis Bank",
        "4" => "Bank of Bahrain and Kuwait",
        "5" => "Bank of Baroda - Corporate Banking",
        "6" => "Bank of Baroda - Retail Banking",
        "7" => "Bank of India",
        "8" => "Bank of Maharashtra",
        "9" => "Canara Bank",
        "10" => "Central Bank of India",
        "11" => "City Union Bank",
        "12" => "Corporation Bank",
        "13" => "Dena Bank",
        "14" => "Deutsche Bank",
        "15" => "Development Credit Bank",
        "16" => "Dhanlaxmi Bank",
        "17" => "Federal Bank",
        "18" => "HDFC Bank",
        "19" => "ICICI Bank",
        "20" => "IDBI Bank",
        "21" => "Indian Bank",
        "22" => "Indian Overseas Bank",
        "23" => "IndusInd Bank",
        "24" => "ING Vysya Bank",
        "25" => "Jammu and Kashmir Bank",
        "26" => "Karnataka Bank Ltd",
        "27" => "Karur Vysya Bank",
        "28" => "Kotak Bank",
        "29" => "Laxmi Vilas Bank",
        "30" => "Oriental Bank of Commerce",
        "31" => "Punjab National Bank - Corporate Banking",
        "32" => "Punjab National Bank - Retail Banking",
        "33" => "Punjab & Sind Bank",
        "34" => "Shamrao Vitthal Co-operative Bank",
        "35" => "South Indian Bank",
        "36" => "State Bank of Bikaner & Jaipur",
        "37" => "State Bank of Hyderabad",
        "38" => "State Bank of India",
        "39" => "State Bank of Mysore",
        "40" => "State Bank of Patiala",
        "41" => "State Bank of Travancore",
        "42" => "Syndicate Bank",
        "43" => "Tamilnad Mercantile Bank Ltd.",
        "44" => "UCO Bank",
        "45" => "Union Bank of India",
        "46" => "United Bank of India",
        "47" => "Vijaya Bank",
        "48" => "Yes Bank Ltd",
    ],
    'otp_valid_hours' => 2,
    /* Recharge Commission Percentage End */
    'pagination_page' => ['page' => 10],
    'bccmail' => 'dalsukh@mnstechnologies.com',
    'expense_under_group' => [
        "Bank Account"  => "Bank Account",
        "Bank OCC A/c"  => "Bank OCC A/c",
        "Bank OD A/c"   => "Bank OD A/c",
        "Current Assets"    => "Current Assets",
        "Current Liabilities"   => "Current Liabilities",
        "Deposits(Asset)"   => "Deposits(Asset)",
        "Direct Expenses"   => "Direct Expenses",
        "Direct Incomes"    => "Direct Incomes",
        "Duties & Taxes"    => "Duties & Taxes",
        "Fixed Assets"  => "Fixed Assets",
        "Indirect Expenses" => "Indirect Expenses",
        "Indirect Incomes"  => "Indirect Incomes",
        "Investment"    => "Investment",
        "Loan & Advances(Asset)"    => "Loan & Advances(Asset)",
        "Loans(Liability)"  => "Loans(Liability)",
        "Provision" => "Provision",
        "Purchase Account" => "Purchase Account",
        "Reserves & Surplus"    => "Reserves & Surplus",
        "Retained Earnings" => "Retained Earnings",
        "Secured Loans" => "Secured Loans",
        "Sundry Creditors"  => "Sundry Creditors",
        "Sundry Debtors"    => "Sundry Debtors",
        "Suspense A/c"  => "Suspense A/c",
        "Unsecured Loans"   => "Unsecured Loans",
        "Advanced & Receivables"    => "Advanced & Receivables",
    ],
    'processes' => [
        'Printing' => 'Printing',
        'Solventless Lamination' => 'Solventless Lamination',
        'Slitting' => 'Slitting',
        'Pouching' => 'Pouching',
        'Rewinding' => 'Rewinding',
        'Extrusion Coating Lamination' => 'Extrusion Coating Lamination',
    ],
    'states' => [
        '01' => 'JAMMU AND KASMIR',
        '02' => 'HIMACHAL PRADESH',
        '03' => 'PUNJAB',
        '04' => 'CHANDIGARH',
        '05' => 'UTTARAKHAND',
        '06' => 'HARYANA',
        '07' => 'DELHI',
        '08' => 'RAJASTHAN',
        '09' => 'UTTAR PRADESH',
        '10' => 'BIHAR',
        '11' => 'SIKKIM',
        '12' => 'ARUNACHAL PRADESH',
        '13' => 'NAGALAND',
        '14' => 'MANIPUR',
        '15' => 'MIZORAM',
        '16' => 'TRIPURA',
        '17' => 'MEGHALAYA',
        '18' => 'ASSAM',
        '19' => 'WEST BENGAL',
        '20' => 'JHARKHAND',
        '21' => 'ORISSA',
        '22' => 'CHHATTISGARH',
        '23' => 'MADHYA PRADESH',
        '24' => 'GUJARAT',
        '26' => 'DADAR AND NAGAR HAVELI',
        '27' => 'MAHARASTRA',
        '29' => 'KARNATAKA',
        '30' => 'GOA',
        '31' => 'LAKSHADWEEP',
        '32' => 'KERALA',
        '33' => 'TAMIL NADU',
        '34' => 'PONDICHERRY',
        '35' => 'ANDAMAN AND NICOBAR',
        '36' => 'TELENGANA',
        '37' => 'ANDHRA PRADESH',
        '38' => 'LADAKH',
        '97' => 'OTHER TERRITORY',
        '96' => 'OTHER COUNTRIES',
    ],
    'bill_categories' => [
        'B2B'    => 'B2B',
        'SEZWP'  => 'SEZWP',
        'SEZWOP' => 'SEZWOP',
        'EXPWP'  => 'EXPWP',
        'EXPWOP' => 'EXPWOP',
        'DEXP'   => 'DEXP',
    ],
    'document_type' => [
        'INV' => "Tax Invoice",
        'CRN' => "Credit Note",
        'DBN' => "Debit Note",
    ],
    'vehicle_type' => [
        'R' => 'Regular',
        'O' => 'ODC',
    ],
    'transport_mode' => [
        '1' => 'Road',
        '2' => 'Rail',
        '3' => 'Air',
        '4' => 'Ship'
    ],
    'units' => [
        'BAG' => 'BAGS',
        'BAL' => 'BALE',
        'BDL' => 'BUNDLES',
        'BKL' => 'BUCKLES',
        'BOU' => 'BILLION OF UNITS',
        'BOX' => 'BOX',
        'BTL' => 'BOTTLES',
        'BUN' => 'BUNCHES',
        'CAN' => 'CANS',
        'CBM' => 'CUBIC METERS',
        'CCM' => 'CUBIC CENTIMETERS',
        'CMS' => 'CENTIMETERS',
        'CTN' => 'CARTONS',
        'DOZ' => 'DOZENS',
        'DRM' => 'DRUMS',
        'GGK' => 'GREAT GROSS',
        'GMS' => 'GRAMMES',
        'GRS' => 'GROSS',
        'GYD' => 'GROSS YARDS',
        'KGS' => 'KILOGRAMS',
        'KLR' => 'KILOLITRE',
        'KME' => 'KILOMETRE',
        'LTR' => 'LITRES',
        'MLT' => 'MILILITRE',
        'MTR' => 'METERS',
        'MTS' => 'METRIC TON',
        'NOS' => 'NUMBERS',
        'OTH' => 'OTHERS',
        'PAC' => 'PACKS',
        'PCS' => 'PIECES',
        'PRS' => 'PAIRS',
        'QTL' => 'QUINTAL',
        'ROL' => 'ROLLS',
        'SET' => 'SETS',
        'SQF' => 'SQUARE FEET',
        'SQM' => 'SQUARE METERS',
        'SQY' => 'SQUARE YARDS',
        'TBS' => 'TABLETS',
        'TGM' => 'TEN GROSS',
        'THD' => 'THOUSANDS',
        'TON' => 'TONNES',
        'TUB' => 'TUBES',
        'UGS' => 'US GALLONS',
        'UNT' => 'UNITS',
        'YDS' => 'YARDS',
    ],
    'countries' => [
        'AD' => 'Andorra',
        'AE' => 'United Arab Emirates',
        'AF' => 'Afghanistan',
        'AG' => 'Antigua and Barbuda',
        'AI' => 'Anguilla',
        'AL' => 'Albania',
        'AM' => 'Armenia',
        'AO' => 'Angola',
        'AQ' => 'Antarctica',
        'AR' => 'Argentina',
        'AS' => 'American Samoa',
        'AT' => 'Austria',
        'AU' => 'Australia',
        'AW' => 'Aruba',
        'AX' => 'Åland Islands',
        'AZ' => 'Azerbaijan',
        'BA' => 'Bosnia and Herzegovina',
        'BB' => 'Barbados',
        'BD' => 'Bangladesh',
        'BE' => 'Belgium',
        'BF' => 'Burkina Faso',
        'BG' => 'Bulgaria',
        'BH' => 'Bahrain',
        'BI' => 'Burundi',
        'BJ' => 'Benin',
        'BL' => 'Saint Barthélemy',
        'BM' => 'Bermuda',
        'BN' => 'Brunei Darussalam',
        'BO' => 'Bolivia (Plurinational State of)',
        'BQ' => 'Bonaire, Sint Eustatius and Saba',
        'BR' => 'Brazil',
        'BS' => 'Bahamas',
        'BT' => 'Bhutan',
        'BV' => 'Bouvet Island',
        'BW' => 'Botswana',
        'BY' => 'Belarus',
        'BZ' => 'Belize',
        'CA' => 'Canada',
        'CC' => 'Cocos (Keeling) Islands',
        'CD' => 'Congo, Democratic Republic of the',
        'CF' => 'Central African Republic',
        'CG' => 'Congo',
        'CH' => 'Switzerland',
        'CI' => 'Côte dIvoire',
        'CK' => 'Cook Islands',
        'CL' => 'Chile',
        'CM' => 'Cameroon',
        'CN' => 'China',
        'CO' => 'Colombia',
        'CR' => 'Costa Rica',
        'CU' => 'Cuba',
        'CV' => 'Cabo Verde',
        'CW' => 'Curaçao',
        'CX' => 'Christmas Island',
        'CY' => 'Cyprus',
        'CZ' => 'Czechia',
        'DE' => 'Germany',
        'DJ' => 'Djibouti',
        'DK' => 'Denmark',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'DZ' => 'Algeria',
        'EC' => 'Ecuador',
        'EE' => 'Estonia',
        'EG' => 'Egypt',
        'EH' => 'Western Sahara',
        'ER' => 'Eritrea',
        'ES' => 'Spain',
        'ET' => 'Ethiopia',
        'FI' => 'Finland',
        'FJ' => 'Fiji',
        'FK' => 'Falkland Islands (Malvinas)',
        'FM' => 'Micronesia (Federated States of)',
        'FO' => 'Faroe Islands',
        'FR' => 'France',
        'GA' => 'Gabon',
        'GB' => 'United Kingdom of Great Britain and Northern Ireland',
        'GD' => 'Grenada',
        'GE' => 'Georgia',
        'GF' => 'French Guiana',
        'GG' => 'Guernsey',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GL' => 'Greenland',
        'GM' => 'Gambia',
        'GN' => 'Guinea',
        'GP' => 'Guadeloupe',
        'GQ' => 'Equatorial Guinea',
        'GR' => 'Greece',
        'GS' => 'South Georgia and the South Sandwich Islands',
        'GT' => 'Guatemala',
        'GU' => 'Guam',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HK' => 'Hong Kong',
        'HM' => 'Heard Island and McDonald Islands',
        'HN' => 'Honduras',
        'HR' => 'Croatia',
        'HT' => 'Haiti',
        'HU' => 'Hungary',
        'ID' => 'Indonesia',
        'IE' => 'Ireland',
        'IL' => 'Israel',
        'IM' => 'Isle of Man',
        'IN' => 'India',
        'IO' => 'British Indian Ocean Territory',
        'IQ' => 'Iraq',
        'IR' => 'Iran (Islamic Republic of)',
        'IS' => 'Iceland',
        'IT' => 'Italy',
        'JE' => 'Jersey',
        'JM' => 'Jamaica',
        'JO' => 'Jordan',
        'JP' => 'Japan',
        'KE' => 'Kenya',
        'KG' => 'Kyrgyzstan',
        'KH' => 'Cambodia',
        'KI' => 'Kiribati',
        'KM' => 'Comoros',
        'KN' => 'Saint Kitts and Nevis',
        'KP' => 'Korea (Democratic Peoples Republic of)',
        'KR' => 'Korea, Republic of',
        'KW' => 'Kuwait',
        'KY' => 'Cayman Islands',
        'KZ' => 'Kazakhstan',
        'LA' => 'Lao Peoples Democratic Republic',
        'LB' => 'Lebanon',
        'LC' => 'Saint Lucia',
        'LI' => 'Liechtenstein',
        'LK' => 'Sri Lanka',
        'LR' => 'Liberia',
        'LS' => 'Lesotho',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'LV' => 'Latvia',
        'LY' => 'Libya',
        'MA' => 'Morocco',
        'MC' => 'Monaco',
        'MD' => 'Moldova, Republic of',
        'ME' => 'Montenegro',
        'MF' => 'Saint Martin (French part)',
        'MG' => 'Madagascar',
        'MH' => 'Marshall Islands',
        'MK' => 'North Macedonia',
        'ML' => 'Mali',
        'MM' => 'Myanmar',
        'MN' => 'Mongolia',
        'MO' => 'Macao',
        'MP' => 'Northern Mariana Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MS' => 'Montserrat',
        'MT' => 'Malta',
        'MU' => 'Mauritius',
        'MV' => 'Maldives',
        'MW' => 'Malawi',
        'MX' => 'Mexico',
        'MY' => 'Malaysia',
        'MZ' => 'Mozambique',
        'NA' => 'Namibia',
        'NC' => 'New Caledonia',
        'NE' => 'Niger',
        'NF' => 'Norfolk Island',
        'NG' => 'Nigeria',
        'NI' => 'Nicaragua',
        'NL' => 'Netherlands',
        'NO' => 'Norway',
        'NP' => 'Nepal',
        'NR' => 'Nauru',
        'NU' => 'Niue',
        'NZ' => 'New Zealand',
        'OM' => 'Oman',
        'PA' => 'Panama',
        'PE' => 'Peru',
        'PF' => 'French Polynesia',
        'PG' => 'Papua New Guinea',
        'PH' => 'Philippines',
        'PK' => 'Pakistan',
        'PL' => 'Poland',
        'PM' => 'Saint Pierre and Miquelon',
        'PN' => 'Pitcairn',
        'PR' => 'Puerto Rico',
        'PS' => 'Palestine, State of',
        'PT' => 'Portugal',
        'PW' => 'Palau',
        'PY' => 'Paraguay',
        'QA' => 'Qatar',
        'RE' => 'Réunion',
        'RO' => 'Romania',
        'RS' => 'Serbia',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'SA' => 'Saudi Arabia',
        'SB' => 'Solomon Islands',
        'SC' => 'Seychelles',
        'SD' => 'Sudan',
        'SE' => 'Sweden',
        'SG' => 'Singapore',
        'SH' => 'Saint Helena, Ascension and Tristan da Cunha',
        'SI' => 'Slovenia',
        'SJ' => 'Svalbard and Jan Mayen',
        'SK' => 'Slovakia',
        'SL' => 'Sierra Leone',
        'SM' => 'San Marino',
        'SN' => 'Senegal',
        'SO' => 'Somalia',
        'SR' => 'Suriname',
        'SS' => 'South Sudan',
        'ST' => 'Sao Tome and Principe',
        'SV' => 'El Salvador',
        'SX' => 'Sint Maarten (Dutch part)',
        'SY' => 'Syrian Arab Republic',
        'SZ' => 'Eswatini',
        'TC' => 'Turks and Caicos Islands',
        'TD' => 'Chad',
        'TF' => 'French Southern Territories',
        'TG' => 'Togo',
        'TH' => 'Thailand',
        'TJ' => 'Tajikistan',
        'TK' => 'Tokelau',
        'TL' => 'Timor-Leste',
        'TM' => 'Turkmenistan',
        'TN' => 'Tunisia',
        'TO' => 'Tonga',
        'TR' => 'Turkey',
        'TT' => 'Trinidad and Tobago',
        'TV' => 'Tuvalu',
        'TW' => 'Taiwan, Province of China',
        'TZ' => 'Tanzania, United Republic of',
        'UA' => 'Ukraine',
        'UG' => 'Uganda',
        'UM' => 'United States Minor Outlying Islands',
        'US' => 'United States of America',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VA' => 'Holy See',
        'VC' => 'Saint Vincent and the Grenadines',
        'VE' => 'Venezuela (Bolivarian Republic of)',
        'VG' => 'Virgin Islands (British)',
        'VI' => 'Virgin Islands (U.S.)',
        'VN' => 'Viet Nam',
        'VU' => 'Vanuatu',
        'WF' => 'Wallis and Futuna',
        'WS' => 'Samoa',
        'YE' => 'Yemen',
        'YT' => 'Mayotte',
        'ZA' => 'South Africa',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ],
    'currencies' => [
        'AED' => 'United Arab Emirates dirham',
        'AFN' => 'Afghan afghani',
        'ALL' => 'Albanian lek',
        'AMD' => 'Armenian dram',
        'ANG' => 'Netherlands Antillean guilder',
        'AOA' => 'Angolan kwanza',
        'ARS' => 'Argentine peso',
        'AUD' => 'Australian dollar',
        'AWG' => 'Aruban florin',
        'AZN' => 'Azerbaijani manat',
        'BAM' => 'Bosnia and Herzegovina convertible mark',
        'BBD' => 'Barbados dollar',
        'BDT' => 'BANGLADESH TAKA',
        'BDT' => 'Bangladeshi taka',
        'BGN' => 'Bulgarian lev',
        'BHD' => 'Bahraini dinar',
        'BIF' => 'Burundian franc',
        'BMD' => 'Bermudian dollar',
        'BND' => 'Brunei dollar',
        'BOB' => 'Boliviano',
        'BOV' => 'Bolivian Mvdol (funds code)',
        'BRL' => 'Brazilian real',
        'BSD' => 'Bahamian dollar',
        'BTN' => 'Bhutanese ngultrum',
        'BWP' => 'Botswana pula',
        'BYN' => 'Belarusian ruble',
        'BZD' => 'Belize dollar',
        'CAD' => 'Canadian dollar',
        'CDF' => 'Congolese franc',
        'CHE' => 'WIR Euro (complementary currency)',
        'CHF' => 'Swiss franc',
        'CHW' => 'WIR Franc (complementary currency)',
        'CLF' => 'Unidad de Fomento (funds code)',
        'CLP' => 'Chilean peso',
        'CNY' => 'Renminbi (Chinese) yuan',
        'COP' => 'Colombian peso',
        'COU' => 'Unidad de Valor Real (UVR) (funds code)',
        'CRC' => 'Costa Rican colon',
        'CUC' => 'Cuban convertible peso',
        'CUP' => 'Cuban peso',
        'CVE' => 'Cape Verdean escudo',
        'CZK' => 'Czech koruna',
        'DJF' => 'Djiboutian franc',
        'DKK' => 'Danish krone',
        'DOP' => 'Dominican peso',
        'DZD' => 'Algerian dinar',
        'EGP' => 'Egyptian pound',
        'ERN' => 'Eritrean nakfa',
        'ETB' => 'Ethiopian birr',
        'EUR' => 'Euro',
        'FJD' => 'Fiji dollar',
        'FKP' => 'Falkland Islands pound',
        'GBP' => 'Pound sterling',
        'GEL' => 'Georgian lari',
        'GHS' => 'Ghanaian cedi',
        'GIP' => 'Gibraltar pound',
        'GMD' => 'Gambian dalasi',
        'GNF' => 'Guinean franc',
        'GTQ' => 'Guatemalan quetzal',
        'GYD' => 'Guyanese dollar',
        'HKD' => 'Hong Kong dollar',
        'HNL' => 'Honduran lempira',
        'HRK' => 'Croatian kuna',
        'HTG' => 'Haitian gourde',
        'HUF' => 'Hungarian forint',
        'IDR' => 'Indonesian rupiah',
        'ILS' => 'Israeli new shekel',
        'INR' => 'Indian rupee',
        'IQD' => 'Iraqi dinar',
        'IRR' => 'Iranian rial',
        'ISK' => 'Icelandic króna',
        'JMD' => 'Jamaican dollar',
        'JOD' => 'Jordanian dinar',
        'JPY' => 'Japanese yen',
        'KES' => 'Kenyan shilling',
        'KGS' => 'Kyrgyzstani som',
        'KHR' => 'Cambodian riel',
        'KMF' => 'Comoro franc',
        'KPW' => 'North Korean won',
        'KRW' => 'South Korean won',
        'KWD' => 'Kuwaiti dinar',
        'KYD' => 'Cayman Islands dollar',
        'KZT' => 'Kazakhstani tenge',
        'LAK' => 'Lao kip',
        'LBP' => 'Lebanese pound',
        'LKR' => 'Sri Lankan rupee',
        'LRD' => 'Liberian dollar',
        'LSL' => 'Lesotho loti',
        'LYD' => 'Libyan dinar',
        'MAD' => 'Moroccan dirham',
        'MDL' => 'Moldovan leu',
        'MGA' => 'Malagasy ariary',
        'MKD' => 'Macedonian denar',
        'MMK' => 'Myanmar kyat',
        'MNT' => 'Mongolian tögrög',
        'MOP' => 'Macanese pataca',
        'MRU' => 'Mauritanian ouguiya',
        'MUR' => 'Mauritian rupee',
        'MVR' => 'Maldivian rufiyaa',
        'MWK' => 'Malawian kwacha',
        'MXN' => 'Mexican peso',
        'MXV' => 'Mexican Unidad de Inversion (UDI) (funds code)',
        'MYR' => 'Malaysian ringgit',
        'MZN' => 'Mozambican metical',
        'NAD' => 'Namibian dollar',
        'NGN' => 'Nigerian naira',
        'NIO' => 'Nicaraguan córdoba',
        'NOK' => 'Norwegian krone',
        'NPR' => 'Nepalese rupee',
        'NZD' => 'New Zealand dollar',
        'OMR' => 'Omani rial',
        'PAB' => 'Panamanian balboa',
        'PEN' => 'Peruvian sol',
        'PGK' => 'Papua New Guinean kina',
        'PHP' => 'Philippine peso',
        'PKR' => 'Pakistani rupee',
        'PLN' => 'Polish zloty',
        'PYG' => 'Paraguayan guaraní',
        'QAR' => 'Qatari riyal',
        'RON' => 'Romanian leu',
        'RSD' => 'Serbian dinar',
        'RUB' => 'Russian ruble',
        'RWF' => 'Rwandan franc',
        'SAR' => 'Saudi riyal',
        'SBD' => 'Solomon Islands dollar',
        'SCR' => 'Seychelles rupee',
        'SDG' => 'Sudanese pound',
        'SEK' => 'Swedish krona/kronor',
        'SGD' => 'Singapore dollar',
        'SHP' => 'Saint Helena pound',
        'SLL' => 'Sierra Leonean leone',
        'SOS' => 'Somali shilling',
        'SRD' => 'Surinamese dollar',
        'SSP' => 'South Sudanese pound',
        'STN' => 'São Tomé and Príncipe dobra',
        'SVC' => 'Salvadoran colón',
        'SYP' => 'Syrian pound',
        'SZL' => 'Swazi lilangeni',
        'THB' => 'Thai baht',
        'TJS' => 'Tajikistani somoni',
        'TMT' => 'Turkmenistan manat',
        'TND' => 'Tunisian dinar',
        'TOP' => 'Tongan pa?anga',
        'TRY' => 'Turkish lira',
        'TTD' => 'Trinidad and Tobago dollar',
        'TWD' => 'New Taiwan dollar',
        'TZS' => 'Tanzanian shilling',
        'UAH' => 'Ukrainian hryvnia',
        'UGX' => 'Ugandan shilling',
        'USD' => 'United States dollar',
        'USN' => 'United States dollar (next day) (funds code)',
        'UYI' => 'Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)',
        'UYU' => 'Uruguayan peso',
        'UYW' => 'Unidad previsional',
        'UZS' => 'Uzbekistan som',
        'VES' => 'Venezuelan bolívar soberano',
        'VND' => 'Vietnamese d?ng',
        'VUV' => 'Vanuatu vatu',
        'WST' => 'Samoan tala',
        'XAF' => 'CFA franc BEAC',
        'XAG' => 'Silver (one troy ounce)',
        'XAU' => 'Gold (one troy ounce)',
        'XBA' => 'European Composite Unit (EURCO) (bond market unit)',
        'XBB' => 'European Monetary Unit (E.M.U.-6) (bond market unit)',
        'XBC' => 'European Unit of Account 9 (E.U.A.-9) (bond market unit)',
        'XBD' => 'European Unit of Account 17 (E.U.A.-17) (bond market unit)',
        'XCD' => 'East Caribbean dollar',
        'XDR' => 'Special drawing rights',
        'XOF' => 'CFA franc BCEAO',
        'XPD' => 'Palladium (one troy ounce)',
        'XPF' => 'CFP franc (franc Pacifique)',
        'XPT' => 'Platinum (one troy ounce)',
        'XSU' => 'SUCRE',
        'XTS' => 'Code reserved for testing',
        'XUA' => 'ADB Unit of Account',
        'XXX' => 'No currency',
        'YER' => 'Yemeni rial',
        'ZAR' => 'South African rand',
        'ZMW' => 'Zambian kwacha',
        'ZWL' => 'Zimbabwean dollar',
    ],
    'google_api_url' => 'https://maps.googleapis.com/maps/api/distancematrix/json',
    'google_geocode_api_url' => 'https://maps.googleapis.com/maps/api/geocode/json',
    'google_api_key' => 'AIzaSyCzSPr8qv5eIyWNd1qpYnYNnUYXDgfmSpM',
    'gstincheck_url' => 'http://sheet.gstincheck.ml/check/5eaa601e1b0563c0c01500cd4b93adb1/',
    'eInvoice' => [
        '24' => [
            'Addr1' => "Plot No 2, Survey No.13/2/P1, NH-27, ",
            'Addr2' => "Nr. Bharudi Toll Plaza",
            'Loc'   => "Pipaliya , Dist-.Rajkot",
            'Pin'   =>  360311,
            'State' => 'Gujarat',
            'IEC'   => ''
        ],
    ],
    'country_codes' => [
        'AD'=>array('name'=>'ANDORRA','code'=>'+376'),
        'AE'=>array('name'=>'UNITED ARAB EMIRATES','code'=>'+971'),
        'AF'=>array('name'=>'AFGHANISTAN','code'=>'+93'),
        'AG'=>array('name'=>'ANTIGUA AND BARBUDA','code'=>'+1268'),
        'AI'=>array('name'=>'ANGUILLA','code'=>'+1264'),
        'AL'=>array('name'=>'ALBANIA','code'=>'+355'),
        'AM'=>array('name'=>'ARMENIA','code'=>'+374'),
        'AN'=>array('name'=>'NETHERLANDS ANTILLES','code'=>'+599'),
        'AO'=>array('name'=>'ANGOLA','code'=>'+244'),
        'AQ'=>array('name'=>'ANTARCTICA','code'=>'+672'),
        'AR'=>array('name'=>'ARGENTINA','code'=>'+54'),
        'AS'=>array('name'=>'AMERICAN SAMOA','code'=>'+1684'),
        'AT'=>array('name'=>'AUSTRIA','code'=>'+43'),
        'AU'=>array('name'=>'AUSTRALIA','code'=>'+61'),
        'AW'=>array('name'=>'ARUBA','code'=>'+297'),
        'AZ'=>array('name'=>'AZERBAIJAN','code'=>'+994'),
        'BA'=>array('name'=>'BOSNIA AND HERZEGOVINA','code'=>'+387'),
        'BB'=>array('name'=>'BARBADOS','code'=>'+1246'),
        'BD'=>array('name'=>'BANGLADESH','code'=>'+880'),
        'BE'=>array('name'=>'BELGIUM','code'=>'+32'),
        'BF'=>array('name'=>'BURKINA FASO','code'=>'+226'),
        'BG'=>array('name'=>'BULGARIA','code'=>'+359'),
        'BH'=>array('name'=>'BAHRAIN','code'=>'+973'),
        'BI'=>array('name'=>'BURUNDI','code'=>'+257'),
        'BJ'=>array('name'=>'BENIN','code'=>'+229'),
        'BL'=>array('name'=>'SAINT BARTHELEMY','code'=>'+590'),
        'BM'=>array('name'=>'BERMUDA','code'=>'+1441'),
        'BN'=>array('name'=>'BRUNEI DARUSSALAM','code'=>'+673'),
        'BO'=>array('name'=>'BOLIVIA','code'=>'+591'),
        'BR'=>array('name'=>'BRAZIL','code'=>'+55'),
        'BS'=>array('name'=>'BAHAMAS','code'=>'+1242'),
        'BT'=>array('name'=>'BHUTAN','code'=>'+975'),
        'BW'=>array('name'=>'BOTSWANA','code'=>'+267'),
        'BY'=>array('name'=>'BELARUS','code'=>'+375'),
        'BZ'=>array('name'=>'BELIZE','code'=>'+501'),
        'CA'=>array('name'=>'CANADA','code'=>'+1'),
        'CC'=>array('name'=>'COCOS (KEELING) ISLANDS','code'=>'+61'),
        'CD'=>array('name'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE','code'=>'+243'),
        'CF'=>array('name'=>'CENTRAL AFRICAN REPUBLIC','code'=>'+236'),
        'CG'=>array('name'=>'CONGO','code'=>'+242'),
        'CH'=>array('name'=>'SWITZERLAND','code'=>'+41'),
        'CI'=>array('name'=>'COTE D IVOIRE','code'=>'+225'),
        'CK'=>array('name'=>'COOK ISLANDS','code'=>'+682'),
        'CL'=>array('name'=>'CHILE','code'=>'+56'),
        'CM'=>array('name'=>'CAMEROON','code'=>'+237'),
        'CN'=>array('name'=>'CHINA','code'=>'+86'),
        'CO'=>array('name'=>'COLOMBIA','code'=>'+57'),
        'CR'=>array('name'=>'COSTA RICA','code'=>'+506'),
        'CU'=>array('name'=>'CUBA','code'=>'+53'),
        'CV'=>array('name'=>'CAPE VERDE','code'=>'+238'),
        'CX'=>array('name'=>'CHRISTMAS ISLAND','code'=>'+61'),
        'CY'=>array('name'=>'CYPRUS','code'=>'+357'),
        'CZ'=>array('name'=>'CZECH REPUBLIC','code'=>'+420'),
        'DE'=>array('name'=>'GERMANY','code'=>'+49'),
        'DJ'=>array('name'=>'DJIBOUTI','code'=>'+253'),
        'DK'=>array('name'=>'DENMARK','code'=>'+45'),
        'DM'=>array('name'=>'DOMINICA','code'=>'+1767'),
        'DO'=>array('name'=>'DOMINICAN REPUBLIC','code'=>'+1809'),
        'DZ'=>array('name'=>'ALGERIA','code'=>'+213'),
        'EC'=>array('name'=>'ECUADOR','code'=>'+593'),
        'EE'=>array('name'=>'ESTONIA','code'=>'+372'),
        'EG'=>array('name'=>'EGYPT','code'=>'+20'),
        'ER'=>array('name'=>'ERITREA','code'=>'+291'),
        'ES'=>array('name'=>'SPAIN','code'=>'+34'),
        'ET'=>array('name'=>'ETHIOPIA','code'=>'+251'),
        'FI'=>array('name'=>'FINLAND','code'=>'+358'),
        'FJ'=>array('name'=>'FIJI','code'=>'+679'),
        'FK'=>array('name'=>'FALKLAND ISLANDS (MALVINAS)','code'=>'+500'),
        'FM'=>array('name'=>'MICRONESIA, FEDERATED STATES OF','code'=>'+691'),
        'FO'=>array('name'=>'FAROE ISLANDS','code'=>'+298'),
        'FR'=>array('name'=>'FRANCE','code'=>'+33'),
        'GA'=>array('name'=>'GABON','code'=>'+241'),
        'GB'=>array('name'=>'UNITED KINGDOM','code'=>'+44'),
        'GD'=>array('name'=>'GRENADA','code'=>'+1473'),
        'GE'=>array('name'=>'GEORGIA','code'=>'+995'),
        'GH'=>array('name'=>'GHANA','code'=>'+233'),
        'GI'=>array('name'=>'GIBRALTAR','code'=>'+350'),
        'GL'=>array('name'=>'GREENLAND','code'=>'+299'),
        'GM'=>array('name'=>'GAMBIA','code'=>'+220'),
        'GN'=>array('name'=>'GUINEA','code'=>'+224'),
        'GQ'=>array('name'=>'EQUATORIAL GUINEA','code'=>'+240'),
        'GR'=>array('name'=>'GREECE','code'=>'+30'),
        'GT'=>array('name'=>'GUATEMALA','code'=>'+502'),
        'GU'=>array('name'=>'GUAM','code'=>'+1671'),
        'GW'=>array('name'=>'GUINEA-BISSAU','code'=>'+245'),
        'GY'=>array('name'=>'GUYANA','code'=>'+592'),
        'HK'=>array('name'=>'HONG KONG','code'=>'+852'),
        'HN'=>array('name'=>'HONDURAS','code'=>'+504'),
        'HR'=>array('name'=>'CROATIA','code'=>'+385'),
        'HT'=>array('name'=>'HAITI','code'=>'+509'),
        'HU'=>array('name'=>'HUNGARY','code'=>'+36'),
        'ID'=>array('name'=>'INDONESIA','code'=>'+62'),
        'IE'=>array('name'=>'IRELAND','code'=>'+353'),
        'IL'=>array('name'=>'ISRAEL','code'=>'+972'),
        'IM'=>array('name'=>'ISLE OF MAN','code'=>'+44'),
        'IN'=>array('name'=>'INDIA','code'=>'+91'),
        'IQ'=>array('name'=>'IRAQ','code'=>'+964'),
        'IR'=>array('name'=>'IRAN, ISLAMIC REPUBLIC OF','code'=>'+98'),
        'IS'=>array('name'=>'ICELAND','code'=>'+354'),
        'IT'=>array('name'=>'ITALY','code'=>'+39'),
        'JM'=>array('name'=>'JAMAICA','code'=>'+1876'),
        'JO'=>array('name'=>'JORDAN','code'=>'+962'),
        'JP'=>array('name'=>'JAPAN','code'=>'+81'),
        'KE'=>array('name'=>'KENYA','code'=>'+254'),
        'KG'=>array('name'=>'KYRGYZSTAN','code'=>'+996'),
        'KH'=>array('name'=>'CAMBODIA','code'=>'+855'),
        'KI'=>array('name'=>'KIRIBATI','code'=>'+686'),
        'KM'=>array('name'=>'COMOROS','code'=>'+269'),
        'KN'=>array('name'=>'SAINT KITTS AND NEVIS','code'=>'+1869'),
        'KP'=>array('name'=>'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','code'=>'+850'),
        'KR'=>array('name'=>'KOREA REPUBLIC OF','code'=>'+82'),
        'KW'=>array('name'=>'KUWAIT','code'=>'+965'),
        'KY'=>array('name'=>'CAYMAN ISLANDS','code'=>'+1345'),
        'KZ'=>array('name'=>'KAZAKSTAN','code'=>'+7'),
        'LA'=>array('name'=>'LAO PEOPLES DEMOCRATIC REPUBLIC','code'=>'+856'),
        'LB'=>array('name'=>'LEBANON','code'=>'+961'),
        'LC'=>array('name'=>'SAINT LUCIA','code'=>'+1758'),
        'LI'=>array('name'=>'LIECHTENSTEIN','code'=>'+423'),
        'LK'=>array('name'=>'SRI LANKA','code'=>'+94'),
        'LR'=>array('name'=>'LIBERIA','code'=>'+231'),
        'LS'=>array('name'=>'LESOTHO','code'=>'+266'),
        'LT'=>array('name'=>'LITHUANIA','code'=>'+370'),
        'LU'=>array('name'=>'LUXEMBOURG','code'=>'+352'),
        'LV'=>array('name'=>'LATVIA','code'=>'+371'),
        'LY'=>array('name'=>'LIBYAN ARAB JAMAHIRIYA','code'=>'+218'),
        'MA'=>array('name'=>'MOROCCO','code'=>'+212'),
        'MC'=>array('name'=>'MONACO','code'=>'+377'),
        'MD'=>array('name'=>'MOLDOVA, REPUBLIC OF','code'=>'+373'),
        'ME'=>array('name'=>'MONTENEGRO','code'=>'+382'),
        'MF'=>array('name'=>'SAINT MARTIN','code'=>'+1599'),
        'MG'=>array('name'=>'MADAGASCAR','code'=>'+261'),
        'MH'=>array('name'=>'MARSHALL ISLANDS','code'=>'+692'),
        'MK'=>array('name'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','code'=>'+389'),
        'ML'=>array('name'=>'MALI','code'=>'+223'),
        'MM'=>array('name'=>'MYANMAR','code'=>'+95'),
        'MN'=>array('name'=>'MONGOLIA','code'=>'+976'),
        'MO'=>array('name'=>'MACAU','code'=>'+853'),
        'MP'=>array('name'=>'NORTHERN MARIANA ISLANDS','code'=>'+1670'),
        'MR'=>array('name'=>'MAURITANIA','code'=>'+222'),
        'MS'=>array('name'=>'MONTSERRAT','code'=>'+1664'),
        'MT'=>array('name'=>'MALTA','code'=>'+356'),
        'MU'=>array('name'=>'MAURITIUS','code'=>'+230'),
        'MV'=>array('name'=>'MALDIVES','code'=>'+960'),
        'MW'=>array('name'=>'MALAWI','code'=>'+265'),
        'MX'=>array('name'=>'MEXICO','code'=>'+52'),
        'MY'=>array('name'=>'MALAYSIA','code'=>'+60'),
        'MZ'=>array('name'=>'MOZAMBIQUE','code'=>'+258'),
        'NA'=>array('name'=>'NAMIBIA','code'=>'+264'),
        'NC'=>array('name'=>'NEW CALEDONIA','code'=>'+687'),
        'NE'=>array('name'=>'NIGER','code'=>'+227'),
        'NG'=>array('name'=>'NIGERIA','code'=>'+234'),
        'NI'=>array('name'=>'NICARAGUA','code'=>'+505'),
        'NL'=>array('name'=>'NETHERLANDS','code'=>'+31'),
        'NO'=>array('name'=>'NORWAY','code'=>'+47'),
        'NP'=>array('name'=>'NEPAL','code'=>'+977'),
        'NR'=>array('name'=>'NAURU','code'=>'+674'),
        'NU'=>array('name'=>'NIUE','code'=>'+683'),
        'NZ'=>array('name'=>'NEW ZEALAND','code'=>'+64'),
        'OM'=>array('name'=>'OMAN','code'=>'+968'),
        'PA'=>array('name'=>'PANAMA','code'=>'+507'),
        'PE'=>array('name'=>'PERU','code'=>'+51'),
        'PF'=>array('name'=>'FRENCH POLYNESIA','code'=>'+689'),
        'PG'=>array('name'=>'PAPUA NEW GUINEA','code'=>'+675'),
        'PH'=>array('name'=>'PHILIPPINES','code'=>'+63'),
        'PK'=>array('name'=>'PAKISTAN','code'=>'+92'),
        'PL'=>array('name'=>'POLAND','code'=>'+48'),
        'PM'=>array('name'=>'SAINT PIERRE AND MIQUELON','code'=>'+508'),
        'PN'=>array('name'=>'PITCAIRN','code'=>'+870'),
        'PR'=>array('name'=>'PUERTO RICO','code'=>'+1'),
        'PT'=>array('name'=>'PORTUGAL','code'=>'+351'),
        'PW'=>array('name'=>'PALAU','code'=>'+680'),
        'PY'=>array('name'=>'PARAGUAY','code'=>'+595'),
        'QA'=>array('name'=>'QATAR','code'=>'+974'),
        'RO'=>array('name'=>'ROMANIA','code'=>'+40'),
        'RS'=>array('name'=>'SERBIA','code'=>'+381'),
        'RU'=>array('name'=>'RUSSIAN FEDERATION','code'=>'+7'),
        'RW'=>array('name'=>'RWANDA','code'=>'+250'),
        'SA'=>array('name'=>'SAUDI ARABIA','code'=>'+966'),
        'SB'=>array('name'=>'SOLOMON ISLANDS','code'=>'+677'),
        'SC'=>array('name'=>'SEYCHELLES','code'=>'+248'),
        'SD'=>array('name'=>'SUDAN','code'=>'+249'),
        'SE'=>array('name'=>'SWEDEN','code'=>'+46'),
        'SG'=>array('name'=>'SINGAPORE','code'=>'+65'),
        'SH'=>array('name'=>'SAINT HELENA','code'=>'+290'),
        'SI'=>array('name'=>'SLOVENIA','code'=>'+386'),
        'SK'=>array('name'=>'SLOVAKIA','code'=>'+421'),
        'SL'=>array('name'=>'SIERRA LEONE','code'=>'+232'),
        'SM'=>array('name'=>'SAN MARINO','code'=>'+378'),
        'SN'=>array('name'=>'SENEGAL','code'=>'+221'),
        'SO'=>array('name'=>'SOMALIA','code'=>'+252'),
        'SR'=>array('name'=>'SURINAME','code'=>'+597'),
        'ST'=>array('name'=>'SAO TOME AND PRINCIPE','code'=>'+239'),
        'SV'=>array('name'=>'EL SALVADOR','code'=>'+503'),
        'SY'=>array('name'=>'SYRIAN ARAB REPUBLIC','code'=>'+963'),
        'SZ'=>array('name'=>'SWAZILAND','code'=>'+268'),
        'TC'=>array('name'=>'TURKS AND CAICOS ISLANDS','code'=>'+1649'),
        'TD'=>array('name'=>'CHAD','code'=>'+235'),
        'TG'=>array('name'=>'TOGO','code'=>'+228'),
        'TH'=>array('name'=>'THAILAND','code'=>'+66'),
        'TJ'=>array('name'=>'TAJIKISTAN','code'=>'+992'),
        'TK'=>array('name'=>'TOKELAU','code'=>'+690'),
        'TL'=>array('name'=>'TIMOR-LESTE','code'=>'+670'),
        'TM'=>array('name'=>'TURKMENISTAN','code'=>'+993'),
        'TN'=>array('name'=>'TUNISIA','code'=>'+216'),
        'TO'=>array('name'=>'TONGA','code'=>'+676'),
        'TR'=>array('name'=>'TURKEY','code'=>'+90'),
        'TT'=>array('name'=>'TRINIDAD AND TOBAGO','code'=>'+1868'),
        'TV'=>array('name'=>'TUVALU','code'=>'+688'),
        'TW'=>array('name'=>'TAIWAN, PROVINCE OF CHINA','code'=>'+886'),
        'TZ'=>array('name'=>'TANZANIA, UNITED REPUBLIC OF','code'=>'+255'),
        'UA'=>array('name'=>'UKRAINE','code'=>'+380'),
        'UG'=>array('name'=>'UGANDA','code'=>'+256'),
        'US'=>array('name'=>'UNITED STATES','code'=>'+1'),
        'UY'=>array('name'=>'URUGUAY','code'=>'+598'),
        'UZ'=>array('name'=>'UZBEKISTAN','code'=>'+998'),
        'VA'=>array('name'=>'HOLY SEE (VATICAN CITY STATE)','code'=>'+39'),
        'VC'=>array('name'=>'SAINT VINCENT AND THE GRENADINES','code'=>'+1784'),
        'VE'=>array('name'=>'VENEZUELA','code'=>'+58'),
        'VG'=>array('name'=>'VIRGIN ISLANDS, BRITISH','code'=>'+1284'),
        'VI'=>array('name'=>'VIRGIN ISLANDS, U.S.','code'=>'+1340'),
        'VN'=>array('name'=>'VIET NAM','code'=>'+84'),
        'VU'=>array('name'=>'VANUATU','code'=>'+678'),
        'WF'=>array('name'=>'WALLIS AND FUTUNA','code'=>'+681'),
        'WS'=>array('name'=>'SAMOA','code'=>'+685'),
        'XK'=>array('name'=>'KOSOVO','code'=>'+381'),
        'YE'=>array('name'=>'YEMEN','code'=>'+967'),
        'YT'=>array('name'=>'MAYOTTE','code'=>'+262'),
        'ZA'=>array('name'=>'SOUTH AFRICA','code'=>'+27'),
        'ZM'=>array('name'=>'ZAMBIA','code'=>'+260'),
        'ZW'=>array('name'=>'ZIMBABWE','code'=>'+263')
    ],
    'week_days' => [
        'Monday' => "Monday",
        'Tuesday' => "Tuesday",
        'Wednesday' => "Wednesday",
        'Thursday' => "Thursday",
        'Friday' => "Friday",
        'Saturday' => "Saturday",
        'Sunday' => "Sunday",
    ],
    'gst_type' =>[
        'Registered' => "Registered",
        'Un-registered' => "Un-registered",
        'Composition' => "Composition",
        'Overseas' => "Overseas",
        'Special Economic Zones' => "Special Economic Zones",
    ],
    'supplier_category' => [
        // 'Supplier' => 'Supplier',
        'Vendor' => 'Vendor',
        // 'Engraver' => 'Engraver',
        'Transporter' => 'Transporter'
    ],

    'marital_status' => ['unmarried' => "Unmarried", 'married' => "Married", 'widowed' => 'Widowed', 'separated' => 'Separated', 'divorced' => 'Divorced'],

    'bloodgroup' => ['O+' => "O+", 'O-' => "O-", 'A+' => "A+", 'A-' => "A-", 'B+' => "B+", 'B-' => "B-", 'AB+' => "AB+",'AB-' => "AB-"],
    'mail_drivers' => [
        "smtp" => "SMTP",
        "mailgun" => "MailGun",
        "mandrill" => "Mandrill",
        "ses" => "SES",
        "sparkpost" => "SparkPost",
        "log" => "Log",
    ],
    'mail_encryption' => [
        '0' => "None",
        'tls' => "TLS",
        'ssl' => "SSL"
    ],
    'lead_activity_priority' => [
        'Low' => 'Low',
        'Medium' => 'Medium',
        'High' => 'High',
    ],
    'type_of_head' => [
        'Assets' => "Assets",
        'Equity' => "Equity",
        'Expense' => "Expense",
        'Fixed Asset' => "Fixed Asset",
        'Income' => "Income",
        'Liability' => "Liability",
    ],

    'leave_type' => [
        'Casual' => 'Casual Leave',
        'Sick' => 'Sick Leave',
    ],

    'duration' => [
        'Full' => 'Full Day',
        'Half' => 'Half Day',
        'Multiple' => 'Multiple Day',
    ],

    'leave_status' => [
        'Pending' => 'Pending',
        'Approved' => 'Approved',
        'Rejected' => 'Rejected',
    ],
    'type_of_head_side' => [
        'Equity' => "Equity",
        'Liability' => "Liability",
        'Assets' => "Assets",
        'Income' => "Assets",
        'Expense' => "Liability",
    ],
    'relation' => [
        'Father' => 'Father',
        'Mother' => 'Mother',
        'Brother' => 'Brother',
        'Sister' => 'Sister',
        'Spouse' => 'Spouse',
        'Friend' => 'Friend',
        'Uncle' => 'Uncle',
        'Cousin brother' => 'Cousin brother',
    ],
    'profit_loss' => [
        "sales" => "Sales",
        "exp" => "Expense",
        "ebidta" => "EBIDTA",
        "int" => "Interest",
        "dep" => "Depreciation",
        "net_other" => "Other Net Income",
        "pbt" => "Profit Before Tax",
        "tax" => "Tax",
        "pat" => "Profit After Tax ",
    ],
    'ratios' => [
        // "gp" => "Gross Profit",
        "ebidta" => "EBIDTA %",
        "bt" => "BT %",
        "icr" => "ICR (Times)",
        "drs" => "Drs. Turnover",
        "crs" => "Crs. Turnover",
        "stock_turnover" => "Stock Turnover",
        "credity_cycle" => "Credit Cycle",
        "1" => "",
        "term_gearing" => "S. Term Gearing",
        "total_gearing" => "Total Gearing",
        "solvability" => "Solvability",
        "c_ratio" => "C. Ratio",
        "quick_ratio" => "Quick Ratio",
        "working_capital" => "Working Capital Position",
    ],
    'balance_sheet_a' => [
        "cash" => "Cash & Like",
        "tdrs" => "TDRs",
        "quick" => "Quick Assets",
        "stock" => "Stock",
        "other_ca" => "Other Assets",
        "total_ca" => "Current Assets",
        "1" => "",
        "fixed_assets" => "Fixed Assets",
        "intangible" => "Intangible/Goodwill",
        "other_fa" => "Other Fixed Assets",
        "total_fa" => "Total Fixed Assets",
        "2"=>"",
        "total_bs_a" => "Total Assets",
    ],

    'balance_sheet_b' => [
        "std" => "STD",
        "tr_crs" => "Tr Crs.",
        "other_cl" => "Other CL",
        "total_cl" => "Total CL",
        "1" => "",
        "long_term" => "Long Term Debt",
        "provision" => "Provision",
        "total_ltd" => "Total LTD",
        "2" => "",
        "equity" => "Equity",
        "retained" => "Retained Earnings",
        "net_worth" => "Net Worth",
        "total_bs_b" => "Total",
    ],
];
